### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [b-babic/peel-prompt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by b-babic** [comment]
I will reach out with pleasure once it's finished. 
Didn't add screenshots so far because it's still work in progress (few things left to be done).

Thanks for reaching out 👋

**Comment by unixorn** [comment]
Cool. When you're done, either create an issue on https://github.com/unixorn/awesome-zsh-plugins or PR in your theme, whatever is most convenient for you.
